### ISSUE TITLE
pypi package have wrong code

### ISSUE THREAD

**Issue by jerzyk** [stephenmcd/django-postgres-fuzzycount#5]
pypi package v. 0.1.6 (wheel) has old code (w/o DJANGO 1.8 fixes)

**Comment by neilhepburn** [comment]
pip version broken in 1.9 :-(  - but latest code here works :-)

**Comment by hakanw** [comment]
+1. I get this error from pypi:

```
  File "/home/ubuntu/allinsights/channels/models.py", line 5, in <module>
    from fuzzycount import FuzzyCountManager
  File "/home/ubuntu/.virtualenvs/production/lib/python3.5/site-packages/fuzzycount.py", line 6, in <module>
    from model_utils.managers import PassThroughManager
ImportError: cannot import name 'PassThroughManager'
```

**Comment by hakanw** [comment]
Actually, even if I use the latest code, I get the above error. Is django fuzzycount broken on Python 3? Or just in general?

**Comment by neilhepburn** [comment]
I use it with python 3 and no problems.  I have only tested up to Django 1.9 however, 1.10 may be broken.

**Comment by hakanw** [comment]
Apparently the problem is that PassthroughManager was removed in django-model-utils 2.4, so you can't upgrade to that.

**Comment by stephenmcd** [comment]
Just pushed 0.1.7 PyPI.
